### ISSUE TITLE
Meta data cell type labels

### ISSUE THREAD

**Issue by MikeDMorgan** [kwells4/mtec_analysis#1]
Hi @kwells4 - thanks for openly sharing your code and data. I am trying to resolve a slight discrepancy between the meta-data cell type labels in the `stage` and `at_stage` columns compared to the labels used in the paper. Specifically, the meta-data (all_meta.csv) contain the following labels:
- Aire_positive
- Ccl21a_high
- Cortico_medullary
- Early_Aire
- Late_Aire
- Tuft

The cell types in your manuscript are labelled cTEC, Ccl21a-high, TAC-TEC, Aire-positive, Late-Aire, Tuft. Is there a simple 1:1 mapping between these 2 sets of annotations, or are these from a different clustering not included in the meta-data? If the latter, would you be so kind as to share these cluster assignments for your data?

Many thanks
Mike

**Comment by kwells4** [comment]
Hi Mike!

Thanks for reaching out! I had completely forgotten that we changed the names for the manuscript. It is a 1:1 mapping

* Aire_positive = Aire-positive
* Ccl21a_high = Ccl21a-high
* Cortico_medullary = cTEC
* Early_Aire = TAC-TEC
* Late_Aire = Late-Aire
* Tuft = Tuft

Hopefully this clears it up for you. I'll close the issue, but let me know if you continue to see a discrepancy.

Best,
Kristen

**Comment by MikeDMorgan** [comment]
Fab, thanks for replying so quickly Kristen.
